name: Import from Google Sheets
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-dictionary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: NPM install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Fetch synsets
        run: npx isv synsets fetch
        env:
          ISV_ENCRYPTION_KEY: ${{ secrets.ISV_ENCRYPTION_KEY }}
          ISV_ENCRYPTION_IV: ${{ secrets.ISV_ENCRYPTION_IV }}
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: synsets
          message: 'synsets: import from new_interslavic_words_list'
          author_name: Medžuslovjansky Bot
          author_email: noreply@interslavic.fun